VirtoCommerce/vc-module-image-tools

- VirtoCommerce.ImageToolsModule.Data/ThumbnailGeneration/ImagesChangesProvider.cs
Introduced filtering of all input files by common image extensions.
> Filter input files by image extensions

- VirtoCommerce.ImageToolsModule.Core/App.config
- VirtoCommerce.ImageToolsModule.Core/VirtoCommerce.ImageToolsModule.Core.csproj
- VirtoCommerce.ImageToolsModule.Core/packages.config
- VirtoCommerce.ImageToolsModule.Data/App.config
- VirtoCommerce.ImageToolsModule.Data/VirtoCommerce.ImageToolsModule.Data.csproj
- VirtoCommerce.ImageToolsModule.Data/packages.config
- VirtoCommerce.ImageToolsModule.Tests/App.config
- VirtoCommerce.ImageToolsModule.Tests/VirtoCommerce.ImageToolsModule.Tests.csproj
- VirtoCommerce.ImageToolsModule.Tests/packages.config
- VirtoCommerce.ImageToolsModule.Web/VirtoCommerce.ImageToolsModule.Web.csproj
- VirtoCommerce.ImageToolsModule.Web/Web.config
- VirtoCommerce.ImageToolsModule.Web/module.manifest
- VirtoCommerce.ImageToolsModule.Web/packages.config
fix for https://github.com/VirtoCommerce/vc-platform/issues/1726
> update VirtoCommerce.Module version

- VirtoCommerce.ImageToolsModule.Data/ThumbnailGeneration/ImagesChangesProvider.cs
- VirtoCommerce.ImageToolsModule.Data/ThumbnailGeneration/ThumbnailGenerationProcessor.cs
- Added suffixes to blob changes cache key as changes should be determined for each set of suffixes;
- Added blob content info caching to avoid reading blob multiple times;
- Added cache for available ThumbnailOption's;
> VP-1650: Rework blob caching

- src/VirtoCommerce.ImageToolsModule.Web/Scripts/blades/task-list.js
> VP-1770: Thumbnails resolutions not displayed

- VirtoCommerce.ImageToolsModule.Web/Scripts/blades/task-list.js
- VirtoCommerce.ImageToolsModule.Web/Scripts/blades/task-list.tpl.html
https://virtocommerce.atlassian.net/browse/VP-1958
> VP-1958: fix context menu for thumbnails

- src/VirtoCommerce.ImageToolsModule.Web/Scripts/blades/task-list.js
- src/VirtoCommerce.ImageToolsModule.Web/Scripts/blades/task-list.tpl.html
https://virtocommerce.atlassian.net/browse/VP-1958
> VP-1958: fix: Context menu buttons not working

- src/VirtoCommerce.ImageToolsModule.Web/module.manifest
https://virtocommerce.atlassian.net/browse/VP-3117
> VP-3117: Fix logo

- src/VirtoCommerce.ImageToolsModule.Web/Scripts/blades/task-detail.js
- src/VirtoCommerce.ImageToolsModule.Web/module.manifest
> VP-3256: Fix ability to save changes with thumbnail:update permission

- src/VirtoCommerce.ImageToolsModule.Web/Scripts/thumbnail.js
VP-6308 Thumbnails generation > incorrect subtitle in notifications
Remove subtitle from template
> VP-6308 Fix wrong subtitle in notification history detail

- src/VirtoCommerce.ImageToolsModule.Web/Scripts/blades/option-detail.js
- src/VirtoCommerce.ImageToolsModule.Web/Scripts/blades/option-list.js
- src/VirtoCommerce.ImageToolsModule.Web/Scripts/blades/task-detail.js
- src/VirtoCommerce.ImageToolsModule.Web/Scripts/blades/task-list.js
- src/VirtoCommerce.ImageToolsModule.Web/Scripts/blades/task-list.tpl.html
> VP-6770: Replace panel action icons

- src/VirtoCommerce.ImageToolsModule.Web/Scripts/blades/task-progress.js
> VP-7045: Icons broken on several pages

- src/VirtoCommerce.ImageToolsModule.Core/VirtoCommerce.ImageToolsModule.Core.csproj
- src/VirtoCommerce.ImageToolsModule.Data/VirtoCommerce.ImageToolsModule.Data.csproj
- src/VirtoCommerce.ImageToolsModule.Web/module.manifest
https://virtocommerce.atlassian.net/browse/PT-207
> PT-207: Enable Source link support

- tests/VirtoCommerce.ImageToolsModule.Tests/ThumbnailGeneratorTests.cs
https://virtocommerce.atlassian.net/browse/PT-1229
> PT-1231: Update ThumbnailGeneratorTests.cs

- src/VirtoCommerce.ImageToolsModule.Web/BackgroundJobs/JobCancellationTokenWrapper.cs
- src/VirtoCommerce.ImageToolsModule.Web/BackgroundJobs/ThumbnailProcessJob.cs
- src/VirtoCommerce.ImageToolsModule.Web/VirtoCommerce.ImageToolsModule.Web.csproj
- src/VirtoCommerce.ImageToolsModule.Web/module.manifest
Reverts VirtoCommerce/vc-module-image-tools#75
> Revert "PT-777: Remove redundant class and update dependencies"

- .github/workflows/main.yml
- .github/workflows/publish_nugets.yml
- Directory.Build.props
- src/VirtoCommerce.ImageToolsModule.Core/VirtoCommerce.ImageToolsModule.Core.csproj
- src/VirtoCommerce.ImageToolsModule.Data/VirtoCommerce.ImageToolsModule.Data.csproj
- src/VirtoCommerce.ImageToolsModule.Web/VirtoCommerce.ImageToolsModule.Web.csproj
- src/VirtoCommerce.ImageToolsModule.Web/module.manifest
- tests/VirtoCommerce.ImageToolsModule.Tests/VirtoCommerce.ImageToolsModule.Tests.csproj
Bump .Net and EF up to 6
https://virtocommerce.atlassian.net/browse/PT-1956
> PT-1956: Bump .Net and EF up to 6

- src/VirtoCommerce.ImageToolsModule.Web/Module.cs
https://virtocommerce.atlassian.net/browse/PT-7292
> PT-7292: Remove redundant BuildServiceProvider from the module startup

- src/VirtoCommerce.ImageToolsModule.Web/package-lock.json
- src/VirtoCommerce.ImageToolsModule.Web/package.json
- src/VirtoCommerce.ImageToolsModule.Web/webpack.config.js
feat: add nodejs-lts support
https://virtocommerce.atlassian.net/browse/PT-9395
> PT-9395: add nodejs-lts support

- README.md
- docs/index.md
- src/VirtoCommerce.ImageToolsModule.Core/Services/IImageService.cs
- src/VirtoCommerce.ImageToolsModule.Core/VirtoCommerce.ImageToolsModule.Core.csproj
- src/VirtoCommerce.ImageToolsModule.Data/Services/DefaultImageService.cs
- src/VirtoCommerce.ImageToolsModule.Data/ThumbnailGeneration/BlobImagesChangesProvider.cs
- src/VirtoCommerce.ImageToolsModule.Data/ThumbnailGeneration/DefaultThumbnailGenerator.cs
- tests/VirtoCommerce.ImageToolsModule.Tests/ThumbnailGeneratorTests.cs
feat: Support Webp image format. WebP is a modern image format that provides superior lossless and lossy compression for images on the web. Using WebP, webmasters and web developers can create smaller, richer images that make the web faster. feat: Update SixLabors.ImageSharp to 3.0.2 version.
feat: Add additional information log. 
https://virtocommerce.atlassian.net/browse/PT-12051
https://virtocommerce.atlassian.net/browse/PT-14014
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ImageTools_3.403.0-pr-103-3873.zip
> PT-14014: Support Webp image format

- src/VirtoCommerce.ImageToolsModule.Web/Scripts/blades/option-detail.tpl.html
clear floats in thumbnail settings blade
https://virtocommerce.atlassian.net/browse/VCST-308
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ImageTools_3.801.0-pr-105-cb5f.zip
> VCST-308: fix UI bugs

- src/VirtoCommerce.ImageToolsModule.Web/Localizations/en.VirtoCommerce.Thumbnail.json
remove "the" and "a"
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ImageTools_3.802.0-pr-106-9ad1.zip
> VCST-538: fix localization

- src/VirtoCommerce.ImageToolsModule.Core/VirtoCommerce.ImageToolsModule.Core.csproj
https://virtocommerce.atlassian.net/browse/VCST-1583
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ImageTools_3.804.0-pr-111-a7e7.zip
> VCST-1583: update SixLabors.ImageSharp
